In [1]:
import sys , os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax,cross_entropy_error
from common.gradient import numerical_gradient


ModuleNotFoundError: No module named 'common'

In [4]:
class simplenet:
    def __init__(self):
        self.W = np.random.randn(2,3)
        
    def predict(self,x):
        return np.dot(x,self.W)
    
    def loss(self , x , t):
        z = self.predict(x) #self는 class 안의 함수를 사용한다는것
        y = softmax(z) #softmax는 class의 함수가 아니기때문에 self 를 쓸 필요가 없다.
        loss = cross_entropy_error(y,t)
        
        return loss

In [19]:
net = simplenet()
print(net.W)
x = np.array([0.6,0.9])
p = net.predict(x)
print(p)
np.argmax(p)
t = np.array([0,0,1])
net.loss(x,t)

[[-0.29744984  0.85135644 -1.13268032]
 [-0.98882903 -1.38388031 -0.81221727]]
[-1.06841603 -0.73467841 -1.41060373]


1.4756490740580648

In [20]:
def f(W):
    return net.loss(x,t)

In [21]:
dW = numerical_gradient(f,net.W)
print(dW)

[[ 0.19315006  0.26967163 -0.46282169]
 [ 0.28972509  0.40450744 -0.69423253]]
